### ISSUE TITLE
indirect_parametrize doesn't work on Pytest 4

### ISSUE THREAD

**Issue by jaraco** [jaraco/suds#3]
Attempting to run the tests with pytest 4.x, they fail:

```
suds main $ python3.9 -m pip-run -q importlib_metadata 'pytest<5' -- -m pytest
WARNING: You are using pip version 21.2.3; however, version 21.2.4 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -m pip install --upgrade pip' command.
======================================================================== test session starts ========================================================================
platform darwin -- Python 3.9.6, pytest-4.6.11, py-1.10.0, pluggy-0.13.1
rootdir: /Users/jaraco/code/main/suds
collected 535 items                                                                                                                                                 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-u1sj0wd_/_pytest/main.py", line 206, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-u1sj0wd_/_pytest/main.py", line 249, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-u1sj0wd_/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-u1sj0wd_/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-u1sj0wd_/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-u1sj0wd_/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-u1sj0wd_/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-u1sj0wd_/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-u1sj0wd_/_pytest/main.py", line 259, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-u1sj0wd_/_pytest/main.py", line 496, in perform_collect
INTERNALERROR>     self.config.pluginmanager.check_pending()
INTERNALERROR>   File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-u1sj0wd_/pluggy/manager.py", line 274, in check_pending
INTERNALERROR>     raise PluginValidationError(
INTERNALERROR> pluggy.manager.PluginValidationError: unknown hook 'pytest_namespace' in plugin <module 'tests.indirect_parametrize' from '/Users/jaraco/code/main/suds/tests/indirect_parametrize.py'>

=================================================================== no tests ran in 0.18 seconds ====================================================================
```

**Comment by jaraco** [comment]
Removing the `pytest_namespace`, the tests still fail when the markers aren't applied:

```
suds main $ python3.9 -m pip-run -q importlib_metadata 'pytest<5' -- -m pytest -k document_literal_request
WARNING: You are using pip version 21.2.3; however, version 21.2.4 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -m pip install --upgrade pip' command.
======================================================================== test session starts ========================================================================
platform darwin -- Python 3.9.6, pytest-4.6.11, py-1.10.0, pluggy-0.13.1
rootdir: /Users/jaraco/code/main/suds
collected 535 items / 534 deselected / 1 selected                                                                                                                   

tests/test_request_construction.py E                                                                                                                          [100%]

============================================================================== ERRORS ===============================================================================
_____________________________________________ ERROR at setup of test_document_literal_request_for_single_element_input ______________________________________________
file /Users/jaraco/code/main/suds/tests/test_request_construction.py, line 100
  @pytest.mark.indirect_parametrize(parametrize_single_element_input_test,
      ("xsd", "external_element_name", "args", "request_body"), (
      # Bare non-optional element.
      ('<xsd:element name="a" type="xsd:integer"/>', "a",
          ([], "<ns0:a/>"),
          ([5], "<ns0:a>5</ns0:a>")),
      # Bare optional element.
      ('<xsd:element name="a" type="xsd:integer" minOccurs="0"/>', "a",
          ([], ""),
          ([5], "<ns0:a>5</ns0:a>")),
      # Choice with a non-empty sub-sequence.
      ("""\
        <xsd:element name="Wrapper">
          <xsd:complexType>
            <xsd:choice>
              <xsd:element name="a" type="xsd:integer"/>
              <xsd:sequence>
                <xsd:element name="b1" type="xsd:integer"/>
                <xsd:element name="b2" type="xsd:integer"/>
              </xsd:sequence>
            </xsd:choice>
          </xsd:complexType>
        </xsd:element>""", "Wrapper",
          ([], "<ns0:Wrapper><ns0:a/></ns0:Wrapper>",
              "non-optional choice handling buggy"),
          ([5], "<ns0:Wrapper><ns0:a>5</ns0:a></ns0:Wrapper>"),
          ([None, 1], "<ns0:Wrapper><ns0:b1>1</ns0:b1><ns0:b2/></ns0:Wrapper>",
              "non-optional choice handling buggy"),
          ([None, 1, 2],
              "<ns0:Wrapper><ns0:b1>1</ns0:b1><ns0:b2>2</ns0:b2></ns0:Wrapper>"),
          ([None, None, 1],
              "<ns0:Wrapper><ns0:b1/><ns0:b2>1</ns0:b2></ns0:Wrapper>",
              "non-optional choice handling buggy")),
      # Choice with a non-optional element.
      ("""\
        <xsd:element name="Wrapper">
          <xsd:complexType>
            <xsd:choice>
              <xsd:element name="a" type="xsd:integer"/>
            </xsd:choice>
          </xsd:complexType>
        </xsd:element>""", "Wrapper",
          ([], "<ns0:Wrapper><ns0:a/></ns0:Wrapper>",
              "non-optional choice handling buggy"),
          ([5], "<ns0:Wrapper><ns0:a>5</ns0:a></ns0:Wrapper>")),
      # Choice with an optional element.
      ("""\
        <xsd:element name="Wrapper">
          <xsd:complexType>
            <xsd:choice>
              <xsd:element name="a" type="xsd:integer" minOccurs="0"/>
            </xsd:choice>
          </xsd:complexType>
        </xsd:element>""", "Wrapper",
          ([], "<ns0:Wrapper/>"),
          ([5], "<ns0:Wrapper><ns0:a>5</ns0:a></ns0:Wrapper>")),
      # Choices with multiple elements, at least one of which is optional.
      ("""\
        <xsd:element name="Wrapper">
          <xsd:complexType>
            <xsd:choice>
              <xsd:element name="a" type="xsd:integer" minOccurs="0"/>
              <xsd:element name="b" type="xsd:integer"/>
            </xsd:choice>
          </xsd:complexType>
        </xsd:element>""", "Wrapper",
          ([], "<ns0:Wrapper/>"),
          ([5], "<ns0:Wrapper><ns0:a>5</ns0:a></ns0:Wrapper>"),
          ([None, 5], "<ns0:Wrapper><ns0:b>5</ns0:b></ns0:Wrapper>")),
      ("""\
        <xsd:element name="Wrapper">
          <xsd:complexType>
            <xsd:choice>
              <xsd:element name="a" type="xsd:integer"/>
              <xsd:element name="b" type="xsd:integer" minOccurs="0"/>
            </xsd:choice>
          </xsd:complexType>
        </xsd:element>""", "Wrapper",
          ([], "<ns0:Wrapper/>"),
          ([5], "<ns0:Wrapper><ns0:a>5</ns0:a></ns0:Wrapper>"),
          ([None, 5], "<ns0:Wrapper><ns0:b>5</ns0:b></ns0:Wrapper>")),
      ("""\
        <xsd:element name="Wrapper">
          <xsd:complexType>
            <xsd:choice>
              <xsd:element name="a" type="xsd:integer" minOccurs="0"/>
              <xsd:element name="b" type="xsd:integer" minOccurs="0"/>
            </xsd:choice>
          </xsd:complexType>
        </xsd:element>""", "Wrapper",
          ([], "<ns0:Wrapper/>"),
          ([5], "<ns0:Wrapper><ns0:a>5</ns0:a></ns0:Wrapper>"),
          ([None, 5], "<ns0:Wrapper><ns0:b>5</ns0:b></ns0:Wrapper>")),
      # Choice with multiple non-empty sub-sequences.
      ("""\
        <xsd:element name="Wrapper">
          <xsd:complexType>
            <xsd:choice>
              <xsd:sequence>
                <xsd:element name="a1" type="xsd:integer"/>
                <xsd:element name="a2" type="xsd:integer"/>
              </xsd:sequence>
              <xsd:sequence>
                <xsd:element name="b1" type="xsd:integer"/>
                <xsd:element name="b2" type="xsd:integer"/>
              </xsd:sequence>
            </xsd:choice>
          </xsd:complexType>
        </xsd:element>""", "Wrapper",
          ([], "<ns0:Wrapper><ns0:a1/><ns0:a2/></ns0:Wrapper>",
              "non-optional choice handling buggy"),
          ([5], "<ns0:Wrapper><ns0:a1>5</ns0:a1><ns0:a2/></ns0:Wrapper>",
              "non-optional choice handling buggy"),
          ([5, 9], """\
            <ns0:Wrapper>
              <ns0:a1>5</ns0:a1>
              <ns0:a2>9</ns0:a2>
            </ns0:Wrapper>"""),
          ([None, 1], "<ns0:Wrapper><ns0:a1/><ns0:a2>1</ns0:a2></ns0:Wrapper>",
              "non-optional choice handling buggy"),
          ([None, None, 1],
              "<ns0:Wrapper><ns0:b1>1</ns0:b1><ns0:b2/></ns0:Wrapper>",
              "non-optional choice handling buggy"),
          ([None, None, 1, 2],
              "<ns0:Wrapper><ns0:b1>1</ns0:b1><ns0:b2>2</ns0:b2></ns0:Wrapper>"),
          ([None, None, None, 1],
              "<ns0:Wrapper><ns0:b1/><ns0:b2>1</ns0:b2></ns0:Wrapper>",
              "non-optional choice handling buggy")),
      # Empty choice.
      ("""\
        <xsd:element name="Wrapper">
          <xsd:complexType>
            <xsd:choice/>
          </xsd:complexType>
        </xsd:element>""", "Wrapper",
          ([], "<ns0:Wrapper/>")),
      # Empty sequence.
      ("""\
        <xsd:element name="Wrapper">
          <xsd:complexType>
            <xsd:sequence/>
          </xsd:complexType>
        </xsd:element>""", "Wrapper",
          ([], "<ns0:Wrapper/>")),
      # Optional choice.
      ("""\
        <xsd:element name="Wrapper">
          <xsd:complexType>
            <xsd:choice minOccurs="0">
              <xsd:element name="a" type="xsd:integer"/>
              <xsd:element name="b" type="xsd:integer"/>
            </xsd:choice>
          </xsd:complexType>
        </xsd:element>""", "Wrapper",
          ([], "<ns0:Wrapper/>",
              # This test passes by accident - the following two bugs seem to
              # cancel each other out:
              #  - choice order indicators explicitly marked optional unsupported
              #  - not constructing correct input parameter values when using no
              #    input arguments for a choice
              #"suds does not yet support minOccurs/maxOccurs attributes on "
              #"all/choice/sequence order indicators"
              ),
          ([5], "<ns0:Wrapper><ns0:a>5</ns0:a></ns0:Wrapper>"),
          ([None, 1],
              "<ns0:Wrapper><ns0:b>1</ns0:b></ns0:Wrapper>")),
      # Optional sequence.
      ("""\
        <xsd:element name="Wrapper">
          <xsd:complexType>
            <xsd:sequence minOccurs="0">
              <xsd:element name="a" type="xsd:integer"/>
              <xsd:element name="b" type="xsd:integer"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>""", "Wrapper",
          ([], "<ns0:Wrapper/>",
              "suds does not yet support minOccurs/maxOccurs attributes on all/"
              "choice/sequence order indicators"),
          ([5], "<ns0:Wrapper><ns0:a>5</ns0:a><ns0:b/></ns0:Wrapper>"),
          ([None, 1],
              "<ns0:Wrapper><ns0:a/><ns0:b>1</ns0:b></ns0:Wrapper>"),
          ([1, 2], """\
              <ns0:Wrapper>
                <ns0:a>1</ns0:a>
                <ns0:b>2</ns0:b>
              </ns0:Wrapper>""")),
      # Sequence with a non-empty sub-sequence.
      ("""\
        <xsd:element name="Wrapper">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="a" type="xsd:integer"/>
              <xsd:sequence>
                <xsd:element name="b1" type="xsd:integer"/>
                <xsd:element name="b2" type="xsd:integer"/>
              </xsd:sequence>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>""", "Wrapper",
          ([], "<ns0:Wrapper><ns0:a/><ns0:b1/><ns0:b2/></ns0:Wrapper>"),
          ([5], "<ns0:Wrapper><ns0:a>5</ns0:a><ns0:b1/><ns0:b2/></ns0:Wrapper>"),
          ([None, 1],
              "<ns0:Wrapper><ns0:a/><ns0:b1>1</ns0:b1><ns0:b2/></ns0:Wrapper>"),
          ([None, 1, 2], """\
              <ns0:Wrapper>
                <ns0:a/>
                <ns0:b1>1</ns0:b1>
                <ns0:b2>2</ns0:b2>
              </ns0:Wrapper>"""),
          ([None, None, 1],
              "<ns0:Wrapper><ns0:a/><ns0:b1/><ns0:b2>1</ns0:b2></ns0:Wrapper>")),
      # Sequence with a non-optional element.
      ("""\
        <xsd:element name="Wrapper">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="a" type="xsd:integer"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>""", "Wrapper",
          ([], "<ns0:Wrapper><ns0:a/></ns0:Wrapper>"),
          ([5], "<ns0:Wrapper><ns0:a>5</ns0:a></ns0:Wrapper>")),
      # Sequence with an optional element.
      ("""\
        <xsd:element name="Wrapper">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="a" type="xsd:integer" minOccurs="0"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>""", "Wrapper",
          ([], "<ns0:Wrapper/>"),
          ([5], "<ns0:Wrapper><ns0:a>5</ns0:a></ns0:Wrapper>")),
      # Sequence with multiple consecutive choices.
      ("""\
        <xsd:element name="Wrapper">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:choice>
                <xsd:element name="aString1" type="xsd:string"/>
                <xsd:element name="anInt1" type="xsd:integer"/>
              </xsd:choice>
              <xsd:choice>
                <xsd:element name="aString2" type="xsd:string"/>
                <xsd:element name="anInt2" type="xsd:integer" minOccurs="0"/>
              </xsd:choice>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>""", "Wrapper",
          ([], "<ns0:Wrapper><ns0:aString1/></ns0:Wrapper>",
              "non-optional choice handling buggy"),
          ([5], "<ns0:Wrapper><ns0:aString1>5</ns0:aString1></ns0:Wrapper>"),
          ([None, 1, 2], """\
              <ns0:Wrapper>
                <ns0:anInt1>1</ns0:anInt1>
                <ns0:aString2>2</ns0:aString2>
              </ns0:Wrapper>"""),
          ([None, 1, None, 2], """\
              <ns0:Wrapper>
                <ns0:anInt1>1</ns0:anInt1>
                <ns0:anInt2>2</ns0:anInt2>
              </ns0:Wrapper>""")),
      # Sequence with multiple optional elements.
      ("""\
        <xsd:element name="Wrapper">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="a" type="xsd:integer" minOccurs="0"/>
              <xsd:element name="b" type="xsd:integer" minOccurs="0"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>""", "Wrapper",
          ([], "<ns0:Wrapper/>"),
          ([5], "<ns0:Wrapper><ns0:a>5</ns0:a></ns0:Wrapper>"),
          ([None, 1], "<ns0:Wrapper><ns0:b>1</ns0:b></ns0:Wrapper>"),
          ([5, 1],
              "<ns0:Wrapper><ns0:a>5</ns0:a><ns0:b>1</ns0:b></ns0:Wrapper>")),
      ))
  def test_document_literal_request_for_single_element_input(xsd,
E       fixture 'xsd' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/jaraco/code/main/suds/tests/test_request_construction.py:100
============================================================== 534 deselected, 1 error in 0.21 seconds ==============================================================
```

Probably due to [this deprecation](https://docs.pytest.org/en/stable/deprecations.html#somefunction-markname).
